[project]
name = "go-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=8.32.0",
    "pydantic>=2.10.6",
]
