from typing import Tuple 

def Transform(s:str) -> str: ...

def Add(a:int, b:int) -> int: ...

def Replace(s:str, old:str, new:str) -> str: ...

def RandomString(n:int) -> str: ...

def MyFunc(a:int, b:str) -> list[int]: ...

def Randn2() -> float: ...

def Rands(n:int) -> list[float]: ...

def Cosine(x:float) -> float: ...

def F2str(x:float) -> str: ...

def F2str2(x:float) -> str: ...

def Str2f(s:str) -> float: ...

def Fff() -> list[str]: ...

def Map_test2() -> Tuple[bytes, str]: ...

def Slice_inp_test(nums:list[int]): ...

def SomeFunc(nums:list[int]): ...

def SomeFunc2(nums:list[str]): ...
